In [1]:
import numpy as np

In [2]:
#normal case- we can store only 1-dimensional array
lst=[1,2,3,4,5,6]
print(lst)

[1, 2, 3, 4, 5, 6]


In [4]:
#using numpy we can store multi dimensional arrays also
print('1D array')
a=np.array([1,2,3,4,5,6,7,8])
print(a)

1D array
[1 2 3 4 5 6 7 8]


In [7]:
print('2D array')
b = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(b)

2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
print('3D array')
c = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])
print(c)

3D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
type(a) #nd array means n dimensional array of data

numpy.ndarray

size tells about the no of elements in an array

In [11]:
print(a.size)
print(b.size)
print(c.size)

8
10
15


shape=(rows,columns)

In [12]:
print(a.shape)
print(b.shape)
print(c.shape)
# it will give the output as eg: (2,5) 2 rows and 5 column

(8,)
(2, 5)
(3, 5)


dtype=type of data present in the array

In [13]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [14]:
# after changing datatype into float - then the int datatype change into float datatype
d=np.array([[1,2,3,4.2,5],
             [6,7,8.9,9,10],
             [11,12,13,14,15]])
print(d.dtype)

float64


arr.transpose()- it will replace the rows into columns and columns into rows

In [15]:
#when we will run the tranpose , it will invert the rows and columns.
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])