In [1]:
#np.empty((rows,cols),dtype)
#here it is containing 2 parameters such as tuples, datatype.
#tuple contain the row and parameters

In [3]:
import numpy as np
np.empty((4,4),dtype=int)

array([[ 94469158978385,               0,    489626271856,
           481036337263],
       [   450971566194,    498216206433,    137438953573,
           476741369961],
       [   498216206435,    137438953580,    476741369958,
           137438953586],
       [   433791696996,    450971566198,    433791696995,
        133457518788608]])

In [8]:
np.empty((4,4),dtype=float)

array([[4.66739657e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [10]:
#first parameter is tuple and second one is dtype
#np.ones((rows,cols),dtype)
#np.ones-
x=np.ones(6) #6- columns
x

array([1., 1., 1., 1., 1., 1.])

In [11]:
y=np.ones((3,5)) #3- rows, 5- columns
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
z=np.ones((4,6),dtype=int) #4- rows, 6- columns, data type= int
z

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [14]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [16]:
b=np.zeros((4,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
c=np.zeros((4,6),dtype=float)
c

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.zeros((4,6),dtype=str)

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

In [21]:
np.ones((4,6),dtype=str)

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [22]:
np.ones((4,6),dtype=bool)

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [23]:
np.zeros((4,6),dtype=bool)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
#np.ones- This function creates a new array of the specified shape and fills it with ones.
#np.empty-This function creates a new array of the specified shape without initializing entries.
        # The values of the array are undefined and will depend on the state of the memory.
#np.zeros- This function creates a new array of the specified shape and fills it with zeros.