In [1]:
import numpy as np
np.random.random(1) # array of 1 element

array([0.09905806])

In [2]:
np.random.random(2) #array contains 2 randomly generated values

array([0.21159208, 0.42565404])

In [3]:
np.random.random((2,2))# 2 dimensional array

array([[0.33426743, 0.84427905],
       [0.2486075 , 0.57435994]])

In [4]:
np.random.random((3,3))# 3 dimensional array

array([[0.92682591, 0.18161927, 0.77893106],
       [0.8563407 , 0.05746035, 0.08880539],
       [0.97661083, 0.23773587, 0.64181566]])

In [6]:
np.random.randint(1,10) # randomly generated value between 1 to 10

8

In [8]:
np.random.randint(1,10,(2,2)) # here it will print 2 d array with the values between  1 to 10

array([[4, 3],
       [1, 8]])

In [12]:
np.random.randint(1,10,(3,4,5))

array([[[2, 9, 3, 9, 9],
        [7, 4, 2, 5, 4],
        [9, 9, 9, 9, 5],
        [3, 5, 5, 1, 8]],

       [[4, 7, 9, 6, 6],
        [9, 5, 4, 1, 3],
        [2, 9, 6, 5, 8],
        [8, 9, 1, 1, 7]],

       [[6, 4, 4, 3, 4],
        [2, 4, 8, 3, 3],
        [6, 9, 5, 7, 6],
        [6, 8, 3, 8, 2]]])

In [13]:
np.random.rand(2,2) # it will give float values ,2d array

array([[0.84135226, 0.82634322],
       [0.70183148, 0.07909428]])

In [14]:
np.random.randn(2,2) # it will give -vely generated float values also  ,2d array

array([[ 0.6216907 , -0.46197181],
       [-1.06814684, -1.12509533]])

In [17]:
a=np.arange(1,10) # arranging values from 1 to 10
print(a)

[1 2 3 4 5 6 7 8 9]


In [18]:
np.random.choice(a)

3